### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by keiosweb** [mossadal/mathjax-plugin#1]
Hi,

I'm mostly here to send my appreciations, although

"Enable MathJax in the backend, so that blog post previews containing mathematical formulas are rendered correctly."

Backend of what? :) There is no word "OctoberCMS" in your Readme, it may be confusing for people, especially those who seek tools like that and find you on github, not October market, what should they do with this plugin really, if they don't know that October exists?

Nevertheless, great job, both this and extended markup plugin.

**Comment by mossadal** [comment]
Thanks. I updated the Readme file.
